import osimport jsonimport timeimport threadingfrom datetime import datetime, timedeltaimport requestsimport feedparserfrom bs4 import BeautifulSoupfrom openai import OpenAIfrom flask import Flask, request, jsonify
# ------------------------------------------------------------------------------# SERVIDOR FLASK# ------------------------------------------------------------------------------app = Flask(__name__)
# CONFIGURACIONES DESDE VARIABLES DE ENTORNO (Render)TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "TU_TELEGRAM_BOT_TOKEN")TELEGRAM_VIP_CHANNEL_ID = os.getenv("TELEGRAM_VIP_CHANNEL_ID", "-100XXXXXXXXXX") # ID del Canal VIP (ej: -1001234567890)BOT_USERNAME = os.getenv("BOT_USERNAME", "TuBotUsername_bot")
OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "TU_OPENAI_KEY")MP_ACCESS_TOKEN = os.getenv("MP_ACCESS_TOKEN", "APP_USR-XXXXXXXXXXXXXXXXXXXX")WEBHOOK_URL = os.getenv("WEBHOOK_URL", "https://tu-app-en-render.onrender.com")SUBSCRIPTION_PRICE = float(os.getenv("SUBSCRIPTION_PRICE", "5000.0")) # Precio mensual en ARS
POSTED_JOBS_FILE = "posted_jobs.json"SUBSCRIBERS_FILE = "subscribers.json"SCAN_INTERVAL_SECONDS = 1800 # Escanear trabajos cada 30 minutos
client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
# ------------------------------------------------------------------------------# MANEJO DE BASE DE DATOS LOCAL (JSON)# ------------------------------------------------------------------------------def load_json_file(filename, default_value):    try:        with open(filename, "r", encoding="utf-8") as f:            return json.load(f)    except (FileNotFoundError, json.JSONDecodeError):        return default_value
def save_json_file(filename, data):    with open(filename, "w", encoding="utf-8") as f:        json.dump(data, f, indent=4, ensure_ascii=False)
# ------------------------------------------------------------------------------# TELEGRAM HELPERS# ------------------------------------------------------------------------------def send_telegram_message(chat_id, text, reply_markup=None):    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"    payload = {        "chat_id": chat_id,        "text": text,        "parse_mode": "Markdown",        "disable_web_page_preview": True    }    if reply_markup:        payload["reply_markup"] = reply_markup    try:        res = requests.post(url, json=payload, timeout=10)        return res.json()    except Exception as e:        print(f" Error al enviar mensaje Telegram: {e}")        return None
def create_one_time_invite_link(channel_id):    """Crea un enlace de invitación único y de 1 solo uso para el canal VIP."""    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/createChatInviteLink"    payload = {        "chat_id": channel_id,        "member_limit": 1,        "name": "Acceso VIP Suscripción"    }    try:        res = requests.post(url, json=payload, timeout=10).json()        if res.get("ok"):            return res["result"]["invite_link"]    except Exception as e:        print(f" Error al crear link de invitación: {e}")    return None
def kick_user_from_channel(channel_id, user_id):    """Banea y desbanea a un usuario para expulsarlo del canal si su membresía venció."""    ban_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/banChatMember"    unban_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/unbanChatMember"    try:        requests.post(ban_url, json={"chat_id": channel_id, "user_id": user_id}, timeout=10)        requests.post(unban_url, json={"chat_id": channel_id, "user_id": user_id, "only_if_banned": True}, timeout=10)        print(f" Usuario {user_id} expulsado del canal VIP por membresía vencida.")    except Exception as e:        print(f" Error al expulsar usuario {user_id}: {e}")
# ------------------------------------------------------------------------------# MERCADO PAGO INTEGRATION# ------------------------------------------------------------------------------def create_mp_preference(user_id):    """Genera preferencia de pago en Mercado Pago."""    url = "https://api.mercadopago.com/checkout/preferences"    headers = {        "Authorization": f"Bearer {MP_ACCESS_TOKEN}",        "Content-Type": "application/json"    }    payload = {        "items": [            {                "title": "Suscripción VIP 30 días - Alertas Empleos Remotos USD",                "quantity": 1,                "unit_price": SUBSCRIPTION_PRICE,                "currency_id": "ARS"            }        ],        "back_urls": {            "success": f"https://t.me/{BOT_USERNAME}"        },        "auto_return": "approved",        "notification_url": f"{WEBHOOK_URL}/webhook/mercadopago",        "external_reference": str(user_id)    }    try:        res = requests.post(url, json=payload, headers=headers, timeout=15).json()        return res.get("init_point")    except Exception as e:        print(f" Error creando preferencia MP: {e}")        return None
@app.route("/webhook/mercadopago", methods=["POST"])def mercadopago_webhook():    """Endpoint para recibir notificaciones automáticas de pago de Mercado Pago."""    data = request.get_json() or {}    payment_id = None        if "data" in data and "id" in data["data"]:        payment_id = data["data"]["id"]    elif request.args.get("data.id"):        payment_id = request.args.get("data.id")    elif request.args.get("id"):        payment_id = request.args.get("id")
    if not payment_id:        return jsonify({"status": "ignored"}), 200
    # Consultar estado del pago en Mercado Pago    payment_url = f"https://api.mercadopago.com/v1/payments/{payment_id}"    headers = {"Authorization": f"Bearer {MP_ACCESS_TOKEN}"}        try:        payment_info = requests.get(payment_url, headers=headers, timeout=15).json()                if payment_info.get("status") == "approved":            user_id = payment_info.get("external_reference")                        if user_id:                subscribers = load_json_file(SUBSCRIBERS_FILE, {})                                # Evitar duplicados                if str(user_id) in subscribers and subscribers[str(user_id)].get("last_payment_id") == str(payment_id):                    return jsonify({"status": "already_processed"}), 200
                # Calcular nueva fecha de vencimiento (30 días desde hoy)                expiration_date = (datetime.now() + timedelta(days=30)).strftime("%Y-%m-%d %H:%M:%S")                                subscribers[str(user_id)] = {                    "user_id": user_id,                    "expiration_date": expiration_date,                    "last_payment_id": str(payment_id),                    "status": "active"                }                save_json_file(SUBSCRIBERS_FILE, subscribers)
                # Generar link único para el Canal VIP                invite_link = create_one_time_invite_link(TELEGRAM_VIP_CHANNEL_ID)                                if invite_link:                    msg = (                        f" *¡PAGO CONFIRMADO EXITOSAMENTE!*\n\n"                        f"Tu suscripción VIP está activa hasta el: `{expiration_date}`\n\n"                        f" *Tu enlace de acceso exclusivo al Canal VIP:*\n{invite_link}\n\n"                        f" _Este enlace es de uso único e personal. No lo compartas._"                    )                else:                    msg = f" *¡Pago confirmado!* Por favor contactá al soporte para obtener tu acceso."
                send_telegram_message(user_id, msg)                print(f" Suscripción activada para el usuario {user_id}")
    except Exception as e:        print(f" Error procesando webhook de MP: {e}")
    return jsonify({"status": "ok"}), 200
@app.route("/")def health_check():    return "Bot VIP de Empleos Remotos & Suscripciones activo 24/7", 200
# ------------------------------------------------------------------------------# CURADOR DE CONTENIDO CON INTELIGENCIA ARTIFICIAL# ------------------------------------------------------------------------------def generate_job_post_ai(title, description, raw_link):    """Utiliza OpenAI para estructurar la oferta de empleo."""    if not client:        return (            f" *{title}*\n\n"            f" *Modalidad:* Remoto Global / USD\n"            f" *Descripción:* {description[:250]}...\n\n"            f" [Postularse Directamente Aquí]({raw_link})"        )
    prompt = f"""    Eres el editor en jefe de un Canal VIP exclusivo de Empleos Remotos en USD.    Toma la siguiente vacante laboral y genera un post atractivo y profesional en Markdown para Telegram.
    Título del puesto: {title}    Descripción: {description}    Link original: {raw_link}
    Estructura exacta requerida:    *Puesto:* [Título en español o inglés]    *Empresa / Cliente:* [Nombre de la empresa o 'Empresa Internacional']    *Ubicación / Modalidad:* 100% Remoto (Global / LatAm)    *Rango Salarial Estimado:* [Sueldo aproximado en USD si figura, sino 'A convenir / Competitivo en USD']    *Requisitos Clave:* [3 bullets resumidos]    *Por qué es una gran oportunidad:* [1 oración de impacto]
    [POSTULARME AL PUESTO DE TRABAJO]({raw_link})    """    try:        response = client.chat.completions.create(            model="gpt-4o-mini",            messages=[{"role": "user", "content": prompt}]        )        return response.choices[0].message.content    except Exception as e:        print(f" Error OpenAI al formatear empleo: {e}")        return f" *{title}*\n\n [Ver vacante y postularse]({raw_link})"
def run_job_scraper():    """Obtiene vacantes de múltiples fuentes globales de empleo remoto."""    print(" Iniciando motor escáner de empleos remotos...")        while True:        timestamp = time.strftime("%H:%M:%S")        print(f"\n [{timestamp}] Buscando nuevas vacantes remota en USD...")        posted_jobs = set(load_json_file(POSTED_JOBS_FILE, []))        new_jobs = []
        # FUENTE 1: WeWorkRemotely RSS        try:            feed = feedparser.parse("https://weworkremotely.com/remote-jobs.rss")            for entry in feed.entries[:10]:                job_id = entry.id if 'id' in entry else entry.link                if job_id not in posted_jobs:                    desc = BeautifulSoup(entry.summary, "html.parser").get_text() if hasattr(entry, 'summary') else ""                    new_jobs.append((job_id, entry.title, desc, entry.link))        except Exception as e:            print(f" Error leyendo WeWorkRemotely: {e}")
        # FUENTE 2: Arbeitnow API (Remotos)        try:            res = requests.get("https://www.arbeitnow.com/api/job-board-api", timeout=15).json()            for job in res.get("data", [])[:10]:                job_id = job.get("slug") or job.get("url")                if job_id and job_id not in posted_jobs and job.get("remote"):                    desc = BeautifulSoup(job.get("description", ""), "html.parser").get_text()                    new_jobs.append((job_id, job.get("title"), desc, job.get("url")))        except Exception as e:            print(f" Error leyendo Arbeitnow API: {e}")
        # Publicar hasta 3 ofertas por ciclo para no saturar el canal        published_count = 0        for job_id, title, description, link in new_jobs:            if published_count >= 3:                break                            print(f" Nueva oferta detectada: {title}")            post_content = generate_job_post_ai(title, description, link)                        # Publicar directamente en el Canal VIP            res = send_telegram_message(TELEGRAM_VIP_CHANNEL_ID, post_content)            if res and res.get("ok"):                posted_jobs.add(job_id)                published_count += 1                time.sleep(5) # Espera entre posts
        save_json_file(POSTED_JOBS_FILE, list(posted_jobs))        print(f" Escaneo finalizado. Publicadas {published_count} nuevas vacantes en el Canal VIP.")                time.sleep(SCAN_INTERVAL_SECONDS)
# ------------------------------------------------------------------------------# COMANDOS DE TELEGRAM Y CONTROL DE EXPIRACIONES# ------------------------------------------------------------------------------def run_telegram_listener():    """Atiende comandos de usuarios por privado (/start, /suscribirse, /estado)."""    print(" Bot Comercial de Telegram escuchando mensajes...")    offset = None        while True:        try:            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"            params = {"timeout": 20, "offset": offset}            response = requests.get(url, params=params, timeout=25).json()                        for update in response.get("result", []):                offset = update["update_id"] + 1                message = update.get("message")                                if message and "text" in message:                    chat_id = message["chat"]["id"]                    text = message["text"].strip().lower()
                    if text in ["/start", "/suscribirse", "suscribirme"]:                        pay_link = create_mp_preference(chat_id)                                                msg = (                            f" *BIENVENIDO AL BOT DE EMPLEOS REMOTOS VIP*\n\n"                            f"Accedé a nuestro *Canal VIP exclusivo* con publicaciones diarias de las mejores vacantes 100% remotas pagadas en USD (LatAm & Global).\n\n"                            f" *Beneficios del Canal VIP:*\n"                            f"• Alertas 24/7 de empleos verificados.\n"                            f"• Salarios promedio de $1.500 a $6.000 USD/mes.\n"                            f"• Links directos de postulación sin intermediarios.\n\n"                            f" *Precio Suscripción:* ${SUBSCRIPTION_PRICE:,.0f} ARS / mes."                        )                                                reply_markup = None                        if pay_link:                            reply_markup = {                                "inline_keyboard": [                                    [{"text": f" PAGAR SUSCRIPCIÓN (${SUBSCRIPTION_PRICE:,.0f} ARS)", "url": pay_link}]                                ]                            }                                                send_telegram_message(chat_id, msg, reply_markup=reply_markup)
                    elif text in ["/estado", "/mi_estado"]:                        subscribers = load_json_file(SUBSCRIBERS_FILE, {})                        sub = subscribers.get(str(chat_id))                                                if sub and sub.get("status") == "active":                            send_telegram_message(chat_id, f" *Tu suscripción VIP está ACTIVA* hasta el: `{sub.get('expiration_date')}`")                        else:                            send_telegram_message(chat_id, " No tenés una suscripción activa actualmente. Usá /suscribirse para ingresar al Canal VIP.")
        except Exception as e:            pass        time.sleep(1)
def run_expiration_checker():    """Revisa diariamente suscriptores vencidos y los remueve del canal."""    while True:        print(" Verificando vencimientos de suscripciones VIP...")        subscribers = load_json_file(SUBSCRIBERS_FILE, {})        now = datetime.now()        updated = False
        for user_id, data in list(subscribers.items()):            if data.get("status") == "active":                exp_date = datetime.strptime(data["expiration_date"], "%Y-%m-%d %H:%M:%S")                if now > exp_date:                    # Expulsar del canal VIP                    kick_user_from_channel(TELEGRAM_VIP_CHANNEL_ID, user_id)                                        # Notificar al usuario por privado                    send_telegram_message(                        user_id,                         " *TU SUSCRIPCIÓN VIP HA VENCIDO*\n\n"                        "Tu acceso al Canal VIP ha finalizado. Para volver a ingresar y no perderte las vacantes en USD, usá el comando /suscribirse."                    )                                        data["status"] = "expired"                    updated = True
        if updated:            save_json_file(SUBSCRIBERS_FILE, subscribers)
        # Chequear cada 12 horas        time.sleep(43200)
# ------------------------------------------------------------------------------# INICIO DE LA APLICACIÓN# ------------------------------------------------------------------------------if __name__ == "__main__":    print(" INICIANDO SISTEMA DE SUSCRIPCIONES Y CANAL VIP DE EMPLEOS REMOTOS")        # 1. Hilo: Listener Comercial de Telegram    threading.Thread(target=run_telegram_listener, daemon=True).start()
    # 2. Hilo: Escáner y Publicador de Empleos    threading.Thread(target=run_job_scraper, daemon=True).start()
    # 3. Hilo: Gestor de Expiraciones de Suscriptores    threading.Thread(target=run_expiration_checker, daemon=True).start()
    # 4. Servidor Web Flask (Hilo Principal)    port = int(os.environ.get("PORT", 10000))    app.run(host="0.0.0.0", port=port)
