import osimport jsonimport timeimport threadingfrom datetime import datetime, timedeltaimport requestsimport feedparserfrom bs4 import BeautifulSoupfrom openai import OpenAIfrom flask import Flask, request, jsonify
app = Flask(__name__)
TELEGRAM_BOT_TOKEN = os.getenv("TELEGRAM_BOT_TOKEN", "")TELEGRAM_VIP_CHANNEL_ID = os.getenv("TELEGRAM_VIP_CHANNEL_ID", "")BOT_USERNAME = os.getenv("BOT_USERNAME", "")OPENAI_API_KEY = os.getenv("OPENAI_API_KEY", "")MP_ACCESS_TOKEN = os.getenv("MP_ACCESS_TOKEN", "")WEBHOOK_URL = os.getenv("WEBHOOK_URL", "")SUBSCRIPTION_PRICE = float(os.getenv("SUBSCRIPTION_PRICE", "5000.0"))
POSTED_JOBS_FILE = "posted_jobs.json"SUBSCRIBERS_FILE = "subscribers.json"SCAN_INTERVAL_SECONDS = 1800
client = OpenAI(api_key=OPENAI_API_KEY) if OPENAI_API_KEY else None
def load_json_file(filename, default_value):    try:        with open(filename, "r", encoding="utf-8") as f:            return json.load(f)    except (FileNotFoundError, json.JSONDecodeError):        return default_value
def save_json_file(filename, data):    with open(filename, "w", encoding="utf-8") as f:        json.dump(data, f, indent=4, ensure_ascii=False)
def send_telegram_message(chat_id, text, reply_markup=None):    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/sendMessage"    payload = {        "chat_id": chat_id,        "text": text,        "parse_mode": "Markdown",        "disable_web_page_preview": True    }    if reply_markup:        payload["reply_markup"] = reply_markup    try:        res = requests.post(url, json=payload, timeout=10)        return res.json()    except Exception as e:        print(f"Error al enviar mensaje Telegram: {e}")        return None
def create_one_time_invite_link(channel_id):    url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/createChatInviteLink"    payload = {        "chat_id": channel_id,        "member_limit": 1,        "name": "Acceso VIP Suscripcion"    }    try:        res = requests.post(url, json=payload, timeout=10).json()        if res.get("ok"):            return res["result"]["invite_link"]    except Exception as e:        print(f"Error al crear link de invitacion: {e}")    return None
def kick_user_from_channel(channel_id, user_id):    ban_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/banChatMember"    unban_url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/unbanChatMember"    try:        requests.post(ban_url, json={"chat_id": channel_id, "user_id": user_id}, timeout=10)        requests.post(unban_url, json={"chat_id": channel_id, "user_id": user_id, "only_if_banned": True}, timeout=10)        print(f"Usuario {user_id} expulsado del canal VIP.")    except Exception as e:        print(f"Error al expulsar usuario {user_id}: {e}")
def create_mp_preference(user_id):    url = "https://api.mercadopago.com/checkout/preferences"    headers = {        "Authorization": f"Bearer {MP_ACCESS_TOKEN}",        "Content-Type": "application/json"    }    payload = {        "items": [            {                "title": "Suscripcion VIP 30 dias - Alertas Empleos Remotos USD",                "quantity": 1,                "unit_price": SUBSCRIPTION_PRICE,                "currency_id": "ARS"            }        ],        "back_urls": {            "success": f"https://t.me/{BOT_USERNAME}"        },        "auto_return": "approved",        "notification_url": f"{WEBHOOK_URL}/webhook/mercadopago",        "external_reference": str(user_id)    }    try:        res = requests.post(url, json=payload, headers=headers, timeout=15).json()        return res.get("init_point")    except Exception as e:        print(f"Error creando preferencia MP: {e}")        return None
@app.route("/webhook/mercadopago", methods=["POST"])def mercadopago_webhook():    data = request.get_json() or {}    payment_id = None    if "data" in data and "id" in data["data"]:        payment_id = data["data"]["id"]    elif request.args.get("data.id"):        payment_id = request.args.get("data.id")    elif request.args.get("id"):        payment_id = request.args.get("id")
    if not payment_id:        return jsonify({"status": "ignored"}), 200
    payment_url = f"https://api.mercadopago.com/v1/payments/{payment_id}"    headers = {"Authorization": f"Bearer {MP_ACCESS_TOKEN}"}    try:        payment_info = requests.get(payment_url, headers=headers, timeout=15).json()        if payment_info.get("status") == "approved":            user_id = payment_info.get("external_reference")            if user_id:                subscribers = load_json_file(SUBSCRIBERS_FILE, {})                if str(user_id) in subscribers and subscribers[str(user_id)].get("last_payment_id") == str(payment_id):                    return jsonify({"status": "already_processed"}), 200
                expiration_date = (datetime.now() + timedelta(days=30)).strftime("%Y-%m-%d %H:%M:%S")                subscribers[str(user_id)] = {                    "user_id": user_id,                    "expiration_date": expiration_date,                    "last_payment_id": str(payment_id),                    "status": "active"                }                save_json_file(SUBSCRIBERS_FILE, subscribers)                invite_link = create_one_time_invite_link(TELEGRAM_VIP_CHANNEL_ID)                if invite_link:                    msg = (                        f" *PAGO CONFIRMADO EXITOSAMENTE*\n\n"                        f"Tu suscripcion VIP esta activa hasta el: `{expiration_date}`\n\n"                        f" *Tu enlace de acceso exclusivo al Canal VIP:*\n{invite_link}\n\n"                        f" _Este enlace es de uso unico y personal._"                    )                else:                    msg = f" *Pago confirmado!* Por favor contacta al soporte."                send_telegram_message(user_id, msg)                print(f"Suscripcion activada para usuario {user_id}")    except Exception as e:        print(f"Error procesando webhook MP: {e}")
    return jsonify({"status": "ok"}), 200
@app.route("/")def health_check():    return "Bot VIP de Empleos Remotos activo 24/7", 200
def generate_job_post_ai(title, description, raw_link):    if not client:        return (            f" *{title}*\n\n"            f" *Modalidad:* Remoto Global / USD\n"            f" *Descripcion:* {description[:250]}...\n\n"            f" [Postularse Directamente Aqui]({raw_link})"        )
    prompt = f"""    Eres el editor de un Canal VIP de Empleos Remotos en USD.    Genera un post atractivo en Markdown para Telegram.
    Titulo: {title}    Descripcion: {description}    Link: {raw_link}
    Estructura requerida:    *Puesto:* [Titulo]    *Empresa:* [Nombre]    *Ubicacion:* 100% Remoto    *Salario:* [Sueldo estimado en USD o Competitivo]    *Requisitos:* [3 puntos]    *Por que aplicar:* [1 oracion]
    [POSTULARME AL PUESTO DE TRABAJO]({raw_link})    """    try:        response = client.chat.completions.create(            model="gpt-4o-mini",            messages=[{"role": "user", "content": prompt}]        )        return response.choices[0].message.content    except Exception as e:        print(f"Error OpenAI: {e}")        return f" *{title}*\n\n [Ver vacante]({raw_link})"
def run_job_scraper():    print("Iniciando motor escaner de empleos...")    while True:        timestamp = time.strftime("%H:%M:%S")        print(f"[{timestamp}] Buscando vacantes...")        posted_jobs = set(load_json_file(POSTED_JOBS_FILE, []))        new_jobs = []
        try:            feed = feedparser.parse("https://weworkremotely.com/remote-jobs.rss")            for entry in feed.entries[:10]:                job_id = entry.id if 'id' in entry else entry.link                if job_id not in posted_jobs:                    desc = BeautifulSoup(entry.summary, "html.parser").get_text() if hasattr(entry, 'summary') else ""                    new_jobs.append((job_id, entry.title, desc, entry.link))        except Exception as e:            print(f"Error WeWorkRemotely: {e}")
        try:            res = requests.get("https://www.arbeitnow.com/api/job-board-api", timeout=15).json()            for job in res.get("data", [])[:10]:                job_id = job.get("slug") or job.get("url")                if job_id and job_id not in posted_jobs and job.get("remote"):                    desc = BeautifulSoup(job.get("description", ""), "html.parser").get_text()                    new_jobs.append((job_id, job.get("title"), desc, job.get("url")))        except Exception as e:            print(f"Error Arbeitnow: {e}")
        published_count = 0        for job_id, title, description, link in new_jobs:            if published_count >= 3:                break            print(f"Nueva oferta: {title}")            post_content = generate_job_post_ai(title, description, link)            res = send_telegram_message(TELEGRAM_VIP_CHANNEL_ID, post_content)            if res and res.get("ok"):                posted_jobs.add(job_id)                published_count += 1                time.sleep(5)
        save_json_file(POSTED_JOBS_FILE, list(posted_jobs))        print(f"Escaneo finalizado. Publicadas: {published_count}")        time.sleep(SCAN_INTERVAL_SECONDS)
def run_telegram_listener():    print("Bot Listener activo...")    offset = None    while True:        try:            url = f"https://api.telegram.org/bot{TELEGRAM_BOT_TOKEN}/getUpdates"            params = {"timeout": 20, "offset": offset}            response = requests.get(url, params=params, timeout=25).json()            for update in response.get("result", []):                offset = update["update_id"] + 1                message = update.get("message")                if message and "text" in message:                    chat_id = message["chat"]["id"]                    text = message["text"].strip().lower()
                    if text in ["/start", "/suscribirse", "suscribirme"]:                        pay_link = create_mp_preference(chat_id)                        msg = (                            f" *BIENVENIDO AL BOT DE EMPLEOS REMOTOS VIP*\n\n"                            f"Accede a nuestro *Canal VIP exclusivo* con publicaciones diarias de vacantes remotas pagadas en USD.\n\n"                            f" *Precio Suscripcion:* ${SUBSCRIPTION_PRICE:,.0f} ARS / mes."                        )                        reply_markup = None                        if pay_link:                            reply_markup = {                                "inline_keyboard": [                                    [{"text": f" PAGAR SUSCRIPCION (${SUBSCRIPTION_PRICE:,.0f} ARS)", "url": pay_link}]                                ]                            }                        send_telegram_message(chat_id, msg, reply_markup=reply_markup)
                    elif text in ["/estado", "/mi_estado"]:                        subscribers = load_json_file(SUBSCRIBERS_FILE, {})                        sub = subscribers.get(str(chat_id))                        if sub and sub.get("status") == "active":                            send_telegram_message(chat_id, f" *Tu suscripcion VIP esta ACTIVA* hasta el: `{sub.get('expiration_date')}`")                        else:                            send_telegram_message(chat_id, " No tienes una suscripcion activa. Usa /suscribirse para ingresar.")        except Exception:            pass        time.sleep(1)
def run_expiration_checker():    while True:        print("Verificando vencimientos...")        subscribers = load_json_file(SUBSCRIBERS_FILE, {})        now = datetime.now()        updated = False        for user_id, data in list(subscribers.items()):            if data.get("status") == "active":                exp_date = datetime.strptime(data["expiration_date"], "%Y-%m-%d %H:%M:%S")                if now > exp_date:                    kick_user_from_channel(TELEGRAM_VIP_CHANNEL_ID, user_id)                    send_telegram_message(user_id, " *TU SUSCRIPCION VIP HA VENCIDO*\n\nUsa /suscribirse para renovar.")                    data["status"] = "expired"                    updated = True        if updated:            save_json_file(SUBSCRIBERS_FILE, subscribers)        time.sleep(43200)
if __name__ == "__main__":    print("INICIANDO BOT VIP")    threading.Thread(target=run_telegram_listener, daemon=True).start()    threading.Thread(target=run_job_scraper, daemon=True).start()    threading.Thread(target=run_expiration_checker, daemon=True).start()    port = int(os.environ.get("PORT", 10000))    app.run(host="0.0.0.0", port=port)
